name: Deploy PITtrackR App to shinyapps.io

on:
  workflow_run:
    workflows: ["Nightly Data Update"]
    types:
      - completed
  workflow_dispatch:     # allows manual runs from GitHub UI
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.1'

    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libgit2-dev \
            gdal-bin \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev \
            libglpk-dev \
            libv8-dev

    - name: Install renv and rsconnect
      run: |
        install.packages(c("renv", "rsconnect"))
      shell: Rscript {0}

    - name: Restore R packages from renv.lock
      run: |
        renv::restore()
      shell: Rscript {0}


    - name: Deploy PITtrackR App to shinyapps.io
      env:
        SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        library(rsconnect)
        rsconnect::setAccountInfo(name = Sys.getenv("SHINYAPPS_NAME"),
                          token = Sys.getenv("SHINYAPPS_TOKEN"),
                          secret = Sys.getenv("SHINYAPPS_SECRET"),
                          server = "shinyapps.io"
                          )
        rsconnect::deployApp(appDir = ".",
        appName = "PITtrackR",
        appFiles = NULL)  # <-- change appName as needed
      shell: Rscript {0}
